/// <reference types="vite/client" />

interface ImportMetaEnv {
  /** Absolute public URL of the site, without trailing slash (see `.env`). */
  readonly VITE_SITE_URL: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}

/** Image presets generated by vite-imagetools (configured in `vite.config.ts`). */
declare module '*?responsive' {
  import type { ResponsivePicture } from '@/config/images'

  const picture: ResponsivePicture
  export default picture
}

declare module '*?thumb' {
  import type { ResponsivePicture } from '@/config/images'

  const picture: ResponsivePicture
  export default picture
}
